[build]
builder = "nixpacks"
buildCommand = "composer install"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"

healthcheckPath = "/"
healthcheckTimeout = 30

[phases.setup]
nixPkgs = ['php81', 'php81Extensions.pdo_mysql', 'composer']
